import Foundation

let utiToExtensionName = [
    "com.apple.dt.swiftpm-package-manifest": "swift",
    "com.apple.dt.playground": "swift",
    "com.apple.dt.playgroundpage": "swift",
    "public.swift-source": "swift",
    "public.c-source": "c",
    "public.c-plus-plus-source": "cc",
    "com.microsoft.csharp-source": "cs",
    "public.c-plus-plus-header": "hpp",
    "public.c-header": "h",
    "public.css": "css",
    "public.html": "html",
    "com.sun.java-source": "java",
    "com.netscape.javascript-source": "js",
    "public.json": "json",
    "org.lesscss.less": "less",
    "public.objective-c-source": "m",
    "public.objective-c-plus-plus-source": "mm",
    "public.protobuf-source": "proto",
    "com.barebones.bbedit.scss-source": "scss",
    "public.tsx": "tsx",
    "public.jsx": "jsx",
    "public.yaml": "yaml",
    "net.daringfireball.markdown": "md",
    "public.xml": "xml",
    "public.ruby-script": "rb",
    "public.python-script": "py",
    "public.shell-script": "sh",
    "public.php-script": "php",
]
